### ISSUE TITLE
Merge Pull Request from fork ( CeciliaDornelas )

### ISSUE THREAD

**Issue by CeciliaDornelas** [cecidoliveira/desafio-github-markdown#2]

**Comment by cecidoliveira** [comment]
- Merge done ✅
[Merge pull request](https://github.com/cecidoliveira/desafio-github-markdown/commit/e3e67dd039394c2435f63a2c731c420109a5879d) https://github.com/cecidoliveira/desafio-github-markdown/pull/1 [from CeciliaDornelas/main](https://github.com/cecidoliveira/desafio-github-markdown/commit/e3e67dd039394c2435f63a2c731c420109a5879d)
